# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Spiritinlife
tagline:          'book of codes'
description:      'This is a personal blog about my coding adventures'
url:              http://spiritinlife.github.io/
baseurl:          /

author:
  name:           'George Chailazopoulos'
  url:            https://twitter.com/_spiritinlife

paginate:         10

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/spiritinlife/spiritinlife.github.io
